insert into tbl_car(id, car_model, car_stock) values (1, 'Toyota Camey', 100)
insert into tbl_car(id, car_model, car_stock) values (2, 'BMW 650', 200)
insert into tbl_car(id, car_model, car_stock) values (3, 'Benz GLC 300', 500)
insert into tbl_car(id, car_model, car_stock) values (4, 'BMW 3', 300)
insert into tbl_car(id, car_model, car_stock) values (5, 'Benz GLC 260', 400)
insert into tbl_car(id, car_model, car_stock) values (6, 'BMW x5', 250)
insert into tbl_car(id, car_model, car_stock) values (7, 'Audi A8', 600)